### ISSUE TITLE
GitHub can now show your private contribution in the commit graph

### ISSUE THREAD

**Issue by Mayeu** [sylvaindurand/private-repos#1]
Hello 👋 
Some time ago GitHub added [added the possibility to show private contribution](https://help.github.com/articles/publicizing-or-hiding-your-private-contributions-on-your-profile/) in the commit graph.
So you may not need this repository anymore :)

**Comment by sylvaindurand** [comment]
Yes, but only if you store your repo on Github!
Here, we are talking about private source code I don't want to share or host on Github, but I still wanted my graph to be updated to reflect my activity!

Thanks anyway :)

**Comment by Mayeu** [comment]
I see :)

Sorry for the noise then :pray:
